spring:

  application:
    name: health-notifications

  datasource:
    url: jdbc:postgresql://localhost:5432/agona
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

telegram:
  bot:
    token: 7472735512:AAFjWV_GRD6bPrNFjZHBR2mJwKakE_3JspA