version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13.2-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=health
      - RABBITMQ_DEFAULT_PASS=1234
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672