spring:
  application:
    name: healthservice-impl

  data:
    mongodb:
      host: localhost
      port: 27017
      database: healthservice

  liquibase:
    change-log: classpath:/db/database-changelog-master.yaml
    enabled: true