spring:
  application:
    name: health-auth-impl

  datasource:
    url: jdbc:postgresql://localhost:5432/agona
    hikari:
      username: admin
      password: admin
      maximum-pool-size: 20
      jdbc-url: jdbc:postgresql://localhost:5432/agona

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql

api:
  github:
    clientId: Ov23ctbCAYSQkwYT2Zzm
    clientSecret: 2611ff36937148d4de1ddcd34c9f2c9b01976918
    scope: read
    tokenType: bearer

jwt:
  expiration:
    access:
      mills: 3600000
    refresh:
      mills: 360000000
  secret: 32wADAS1vnn2321fvsGENbsnbdnskbESFEGVESBVSBFEREAWEVDVEGEVETEVESGESFSEGVSGESF23w32423423432

server:
  port: 8082

